feat: saving comments and bookings
lineday1159/java-shareit pull request #3
Opened 2023-06-19 21:50 UTC by lineday1159

2023-06-20 21:28 UTC, zgreen3 requested changes
Привет. 
Проверил проект, в целом он соответствует ТЗ, отлично.
Комментариев не много, потому что основные пункты ТЗ соблюдены и использование пройденных в спринте механизмов Spring и Spring Boot технически корректно. 
После принятия к сведению комментариев, присылай работу на завершение проверки.
Спасибо.

2023-06-20 21:28 UTC, zgreen3 commented on src/main/resources/schema.sql
> +CREATE TABLE IF NOT EXISTS users (
Отлично:

Вижу, что здесь корректно написаны DDL SQL-выражения для создания таблиц для основных сущностей проекта (причём, даже не только для Item и User, как требовалось по ТЗ), отлично!

Для информации:

Полезно иметь ввиду, что в синтаксисе PostgreSQL допустимы разные варианты указания внешнего ключа: https://stackoverflow.com/a/28560619 , на разных рабочих проектах могут встретиться все 4, какое-либо предпочтение между ними сложно определить, поэтому выбор синтаксиса обычно зависит от договорённостей внутри команды проекта (общего для команды стиля написания sql-кода).

2023-06-20 21:28 UTC, zgreen3 commented on src/main/java/ru/practicum/shareit/user/model/User.java
> +@Table(name = "users", schema = "public")
Отлично:

Вижу, что ты разобрался в написании основных классов сущностей (моделей) для репозиториев данного проекта с использованием аннотаций JPA, отлично!

2023-06-20 21:28 UTC, zgreen3 commented on src/main/resources/schema.sql
> +);
Надо исправить:

Не увидел в изменениях к проекту добавления параметров доступа к базе данных в файл `application.properties` (именно их Spring будет использовать при выполнении скрипта schema.sql, а также при дальнейшей работе приложения).

Подсказка:
имеются ввиду примерно такие строки (значения нужно заполнить) в файле `application.properties`: 
```
#---
spring.datasource.driverClassName=
spring.datasource.url=
spring.datasource.username=
spring.datasource.password=
```

2023-06-20 21:28 UTC, zgreen3 commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +    @Transactional(readOnly = true)
Отлично:

Вижу, что в целом корректно (в соответствии со схемой БД и с описаниями в ТЗ) доработаны репозитории, а также сервисы для Item и User, отлично!

2023-06-21 09:24 UTC, lineday1159 commented on src/main/resources/schema.sql
> +);
Когда прописываю свои значения, начинают падать автотесты, так как в автотестах используются параметры подключения используемые в дефолте

2023-06-21 18:46 UTC, lineday1159 commented
Когда прописываю свои значения, начинают падать автотесты, так как в автотестах используются параметры подключения используемые в дефолте

2023-06-21 21:14 UTC, zgreen3 commented on src/main/resources/schema.sql
> +);
Хм, похоже, тогда нужно смотреть детали, какие значения ты указываешь, вероятно, что-то могло быть случайно указано не так, как ожидают автотесты (они, насколько я помню, используют для проверки тестовое подключение к H2 БД, так что не должны падать из-за добавления данных по основной БД.

Напоминаю, что важно сохранять вот эти комментарии вверху каждой конфигурации, "#--" - это неяавная (для читающего код)) подсказка Спринг-у, что далее идёт конфигурация для одного из окружений (по умолчанию - для prod-акшен-окружения).

Для информации, значения параметров, с которыми автотесты точно работают (это неоднократно проверялось), таковы:

```
#---
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5434/shareit
spring.datasource.username=shareit
spring.datasource.password=shareit
```

В любом случае, поскольку для учебных целей дальнейшее углубление в решение данного конкретного вопроса не видится мне критически важным, а иных комментариев типа "Надо исправить" у меня не было, готов, в таком случае, принять проект в текущем виде=).

2023-06-21 21:15 UTC, zgreen3 approved these changes
Принимаю проект в текущем виде, встретимся на проверке следующих проектов.

2023-06-29 12:38 UTC, merged