fix: adding test and requests
lineday1159/java-shareit pull request #4
Opened 2023-07-03 09:52 UTC by lineday1159

2023-07-03 10:28 UTC, lineday1159 commented
Почему-то не прошёл по кол-ву проверенного кода, хотя в intelijIdea у меня совсем другие цифры.

Очень прошу проверить текущий код, я сегодня добью, что есть

2023-07-03 22:25 UTC, zgreen3 requested changes
Привет.

Проверил проект, в целом он соответствует ТЗ, отлично.

При этом важно добиться того, чтобы все тесты в проекте завершались успешно перед следующей итерацией проверки работы ревьюером, т.к. для будущей работы на реальных проектах навык покрытия тестами функционала приложения для бекэнд программиста очень нужен, и именно такой практической работой, как в данном спринте, может, немного занудной с виду, но критически необходимой для корректного функционирования приложения, можно этот навых развить.

Если возникнут какие-либо вопросы по новым тестам, советую также обратиться за разъяснениями к наставнику и, может, даже в чат когорты, т.к. эти тесты давно отлажены (уже десятки, если не больше, работ проверены, где они все "зелёные") и ревьюеры обычно проверяют работы в части, в которой сложно написать автотесты (у меня, к слову, также формально нет возможности принять работу с падающими автотестами, за этим следит платформа Практикума).

Поэтому желаю терпения и успехов в доработке оставшихся авто-тестов и на следующей итерации жду работу для завершения проверки.

2023-07-03 22:25 UTC, zgreen3 commented on src/main/java/ru/practicum/shareit/request/ItemRequestController.java
> +        return requestService.create(itemRequestDto, userId);
Можно лучше:

Здесь имеет смысл также залогировать значение параметра itemRequestDTO и userId, чтобы иметь возможность мониторить работу данного метода 
(напоминаю, что для удобства создания логгера можно перед именем класса использовать аннотацию Lombok @Slf4j , https://projectlombok.org/api/lombok/extern/slf4j/Slf4j).

В логировании запросов полезно использовать т.н. placeholder "{}" с параметрами из запроса, т.е., например, `log.info("POST request to add an item request with userId: {}", userId);` (чтобы не получить в логах вида `log.info("POST request to add an item request");` множество одинаковых сообщений без возможности определить, какой это конкретно запрос в каждом случае).

Аналогичный комментарий справедлив и для других методов контроллера.

2023-07-03 22:25 UTC, zgreen3 commented on src/main/java/ru/practicum/shareit/request/service/RequestServiceImpl.java
> +            itemRequestWithItemDtos.add(ItemRequestMapper.toRequestItemWithItemDto(itemRequest, itemRepository.findByRequestId(itemRequest.getId())));
Для информации:

В более крупном проекте (где ожидается ежесекундная нагрузка на БД) оптимальнее было бы сделать соединение (JOIN) данных из таблицы запросов и таблицы вещей, чем для каждого itemRequest запрашивать в БД связанные с ним вещи. 

При этом читабельность данного решения (что реализована в коде проекта - с циклом по itemRequest и запросом данных о вещах для каждого itemRequest) - выше, а значит, риски ошибки в логике работы - ниже.

2023-07-03 22:25 UTC, zgreen3 commented on src/main/java/ru/practicum/shareit/request/service/RequestServiceImpl.java
> +        List<ItemRequest> itemRequests = requestRepository.findAllByRequesterId(userId);
Надо исправить:

В ТЗ указано, что "Запросы должны возвращаться в отсортированном порядке от более новых к более старым".

Нужно добавить эту сортировку на уровне репозитория (подсказка: для таких случаев подходит наследование пользовательского интерфейса репозитория от JpaRepository<...> с методом вроде такого, `List<ItemRequest> findByUser_Id(Long id, Sort sort);` [или `requestRepository.findAllByRequestorIdOrderByCreatedDesc(userId); `] - указал объявление метода как пример, без привязки имён к коду твоего проекта).

2023-07-03 22:25 UTC, zgreen3 commented on src/main/java/ru/practicum/shareit/request/service/RequestServiceImpl.java
> +        Pageable pageable = PageRequest.of(from / size, size, Sort.by("created"));
Отлично:

Здорово, что здесь также предусмотрена пагинация, для любого API (даже внутреннего) - это (помимо прочих очевидных моментов, связанных с оптимизацией производительности приложения за счёт снижения нагрузки на объём передаваемых БД данныхв единицу времени) также хорошая защита от случайных или намеренных (D)DoS-атак.

2023-07-03 22:25 UTC, zgreen3 commented on src/main/java/ru/practicum/shareit/request/ItemRequestController.java
> +                                                           @RequestParam(defaultValue = "0") int from,
Можно лучше:

Сюда можно добавить аннотацию (для валидации поля from - в дополнение к @Valid) `@PositiveOrZero` (https://javaee.github.io/javaee-spec/javadocs/javax/validation/constraints/PositiveOrZero.html), а для следующего параметра - `@Positive` (https://javaee.github.io/javaee-spec/javadocs/javax/validation/constraints/Positive.html). 

Кстати, набор самых употребимых из таких аннотаций см., например, здесь, https://www.logicbig.com/tutorials/java-ee-tutorial/bean-validation/predefined_constraints.html

2023-07-03 22:25 UTC, zgreen3 commented on src/main/java/ru/practicum/shareit/request/ItemRequestController.java
> +    @GetMapping("/{requestId}")
Отлично:

Вижу, что новые endpoint-ы добавлены здесь в полном соответствие с ТЗ.

2023-07-03 22:25 UTC, zgreen3 commented on src/main/java/ru/practicum/shareit/item/dto/ItemDto.java
> +    private Long requestId;
Можно по-другому:

Хотя просто добавить новое поле requestId в этот класс, ItemDto, в соответствие с ТЗ вполне допустимо, можно также указать над классом или над данным полем аннотацию `@JsonInclude(JsonInclude.Include.NON_NULL)`, чтобы уже на данном уровне учесть момент из ТЗ о том, "что должна сохраниться возможность добавить вещь и БЕЗ указания requestId".

2023-07-03 22:25 UTC, zgreen3 commented on src/test/java/ru/practicum/shareit/user/UserControllerTest.java
> +@WebMvcTest(controllers = UserController.class)
Отлично:

Вижу, что ты разобрался с тестовыми слайсами, прекрасно! Это всегда полезно использовать для сокращения времени запуска и упрощения создания и  инициализации интеграционных тестов в приложении.

Кстати, советую в тестовых методах при длинных инициализациях (в реализованных тестовых классах технически - всё нормально, это просто примечание для информации)) до вызова тестируемого метода писать в тестовом-методе комментарий "//given", над самим тестируемым методом - "//when", а перед группой ассёртов - "//then" (https://en.wikipedia.org/wiki/Given-When-Then#:~:text=Given-When-Then%20(GWT,words%20given%2C%20when%20and%20then. , https://martinfowler.com/bliki/GivenWhenThen.html), такой подход поможет быстро визуально выделять нужные части длинного тестового метода, а если на проекте будет потом использоваться Cucumber или подобный BDD-фреймворк, то его применение будет привычнее команде, привыкшей так структурировать юнит-тесты.

2023-07-03 22:25 UTC, zgreen3 commented on src/test/java/ru/practicum/shareit/user/UserControllerTest.java
> +    @MockBean
Отлично:

Вижу, что в полном соответствии с ТЗ реализованы тесты для REST-эндпоинтов приложения с использованием MockMVC, 
а также, что ты разобрался с работой с моками в Mockito, молодец!

Отмечу лишь, что иногда, хотя редко, в легаси-проектах где много технического долга, может пригодиться использование т.н. spy, 
https://www.baeldung.com/mockito-spy (хотя обычно это признак необходимости рефакторинга тестируемого класса), для spy также может пригодиться синтаксис do-return, вместо when-then, https://stackoverflow.com/a/29394497.
Также может пригодиться для тестирования работы методов, когда надо "замокать" выбрасывание исключений, thenThrow(...) синтаксис, https://www.baeldung.com/mockito-exceptions .

2023-07-03 22:25 UTC, zgreen3 commented on src/test/java/ru/practicum/shareit/request/service/RequestServiceImplTest.java
> +@SpringBootTest
Отлично:

Вижу, что ты также разобрался с не самой простой, но важной для полноценного тестирования приложения темой интергационных тестов!

2023-07-03 22:25 UTC, zgreen3 commented on src/test/java/ru/practicum/shareit/item/repository/ItemRepositoryTest.java
> +@DataJpaTest
Отлично:

Вижу, что ты также разобрался с DataJpaTest-ами, замечательно!

2023-07-03 22:25 UTC, zgreen3 commented on src/test/java/ru/practicum/shareit/request/ItemRequestControllerTest.java
> +                        .content(mapper.writeValueAsString(itemRequestDto))
Отлично:

Вижу, что все основные тесты, необходимые по ТЗ, у тебя в проекте присутствуют, так держать!

При этом, поскольку не обнаружил в коде проекта кастомных реализаций сериализации / десериализации в JSON (точнее, классов с аннотацией @JsonComponent), то требование ТЗ про "реализацию тестов для работы с JSON для DTO в приложении с помощью аннотации @JsonTest" можно считать не относящимся к данному проекту=). В любом случае, советую ознакомиться с возможностями применения этой аннотации в Spring Boot-проектах, см. краткое описание с примером, на англ. яз., например, тут: https://www.arhohuttunen.com/spring-boot-jsontest/
"

2023-07-04 20:41 UTC, zgreen3 approved these changes
Привет, вижу, что комментарии по коду были приняты во внимание (+формально, теперь все авто-тесты завершаются успешно), критические замечания к коду отсутствуют, поэтому считаю, что учебные цели данной работы достигнуты, принимаю проект в текущем виде, встретимся на проверке следующих проектов.

И успехов в освоении важной (и вполне посильной)) темы про докер-контейнеры!

2023-07-04 20:41 UTC, zgreen3 commented on pom.xml
> +                        <excludes>
Мудрый ход=), хотя в следующих проектах прошу так не делать, потому что в рамках учебного проекта тестирование, например, классов мапперов, также важно для практической отработки, как и других.

2023-07-08 08:05 UTC, merged